config/routes.rb
Rails.application.routes.draw do
  root 'yoin#top'
  resources :users, only: %w(new create edit update show destroy) do
    member do
      get :following, :followers, :collection
    end
  end
  resources :sessions, only: %w(new create destroy)
  resources :senryus, only: %w(new create destroy) do
    collection do
      get :discover, :home
    end
    resources :favorites, only: %w(create destroy)
  end
  resources :relationships, only: %w(create destroy)
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :senryu, counter_cache: :favorites_count
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_senryu

  def create
    Favorite.create(user_id: current_user.id, senryu_id: params[:senryu_id])
    @senryu.reload
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, senryu_id: params[:senryu_id])
    favorite.destroy
    @senryu.reload
  end

  private

  def set_senryu
    @senryu = Senryu.find(params[:senryu_id])
  end

end

app/views/favorites/_favorite.html.erb
<% if senryu.favorited(current_user.id).blank? %>
  <%= link_to senryu_favorites_path(senryu.id), id: "favorite_senryu_#{senryu.id}", method: :post, remote: true do %>
    <i class="far fa-heart"></i>
    <%= senryu.favorites_count unless senryu.favorites_count == 0 || nil %>
  <% end %>
<% else %>
  <%= link_to senryu_favorite_path(senryu_id: senryu.id, id: senryu.favorites[0].id), id: "favorite_senryu_#{senryu.id}", class: "red-heart", method: :delete, remote: true do %>
    <i class="fas fa-heart"></i>
    <%= senryu.favorites_count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @senryu.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {senryu: @senryu}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @senryu.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {senryu: @senryu}) %>");