config/routes.rb
Rails.application.routes.draw do
  root 'yoin#top'
  resources :users, only: %w(new create edit update show destroy) do
    member do
      get :following, :followers, :collection
    end
  end
  resources :sessions, only: %w(new create destroy)
  resources :senryus, only: %w(new create destroy) do
    collection do
      get :discover, :home
    end
    resources :favorites, only: %w(create destroy)
  end
  resources :relationships, only: %w(create destroy)
end

app/views/headers_footers/_collection_header.html.erb
<div class="header collection-header">
  <h5><%= I18n.t('views.my_collection') %></h5>
  <p><%= I18n.t('views.posts_you_liked') %></p>
</div>
<%= render 'headers_footers/nav_bar' %>

app/views/headers_footers/_home_header.html.erb
<div class="header home-header">
  <h1 >Yoin</h1>
    <i class="fas fa-bars"></i>
    <ul class="acd-menu-item">
      <li><%= link_to I18n.t('views.home'), home_senryus_path %></li>
      <li><%= link_to I18n.t('views.discover'), discover_senryus_path %></li>
      <li><%= link_to I18n.t('views.my_page'), user_path(current_user.id) %></li>
      <li><%= link_to I18n.t('views.compose'), new_senryu_path %></li>
      <li><%= link_to I18n.t('views.logout'), session_path(current_user.id), class: "logout", method: :delete %></li>
    </ul>
  </ul>
</div>
<%= render 'headers_footers/nav_bar' %>

app/views/headers_footers/_nav_bar.html.erb
<%# 色は仮 #%>
<div class="nav-bar">
  <% if current_page?(controller: 'senryus', action: 'home') %>
    <div class="tab active purple">
      <%= link_to home_senryus_path do %>
        <i class="fas fa-mountain"></i>
      <% end %>
      <p>Home</p>
    </div>
    <div class="tab pink">
      <%= link_to discover_senryus_path do %>
        <i class="fas fa-compass"></i>
      <% end %>
      <p>Discover</p>
    </div>
  <% elsif current_page?(controller: 'senryus', action: 'discover') %>
    <div class="tab purple">
      <%= link_to home_senryus_path do %>
        <i class="fas fa-mountain"></i>
      <% end %>
      <p>Home</p>
    </div>
    <div class="tab active pink">
      <%= link_to discover_senryus_path do %>
        <i class="fas fa-compass"></i>
      <% end %>
      <p>Discover</p>
    </div>
  <% else %>
    <div class="tab purple">
      <%= link_to home_senryus_path do %>
        <i class="fas fa-mountain"></i>
      <% end %>
      <p>Home</p>
    </div>
    <div class="tab pink">
      <%= link_to discover_senryus_path do %>
        <i class="fas fa-compass"></i>
      <% end %>
      <p>Discover</p>
    </div>
  <% end %>
  <div class="tab yellow">
    <%= link_to user_path(current_user.id) do %>
      <i class="fas fa-user"></i>
    <% end %>
    <p>Profile</p>
  </div>
  <div class="tab teal">
    <%= link_to new_senryu_path do %>  
      <i class="fas fa-pen-nib"></i>
    <% end %>
    <p>Compose</p>
  </div>
</div>

app/views/headers_footers/_notification_footer.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> notification-footer">
    <%= message %>
  </div>
<% end %>

app/views/headers_footers/_relationship_header.html.erb
<div class="relationship-header">
  <% if current_page?(controller: 'users', action: 'following') %>
    <div class="relationship-numbers active">
      <%= link_to following_user_path(@user.id) do %>
        <%= @user.following.size %>&nbsp;<%= I18n.t('views.following') %>
      <% end %>
    </div>
    <div class="relationship-numbers">
      <%= link_to followers_user_path(@user.id) do %>
        <%= @user.followers.size %>&nbsp;<%= I18n.t('views.followers') %>
      <% end %>
    </div>
  <% elsif current_page?(controller: 'users', action: 'followers') %>
    <div class="relationship-numbers">
      <%= link_to following_user_path(@user.id) do %>
        <%= @user.following.size %>&nbsp;<%= I18n.t('views.following') %>
      <% end %>
    </div>
    <div class="relationship-numbers active">
      <%= link_to followers_user_path(@user.id) do %>
        <%= @user.followers.size %>&nbsp;<%= I18n.t('views.followers') %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/headers_footers/_search_header.html.erb
<div class="header search-header">
  <%= form_with(model: @senryus, local: true, method: :get, url: discover_senryus_path) do |f| %>
    <input class="useFontAwesomeFamily" type="text" placeholder="<%= I18n.t('views.search_senryus') %>" name="senryu[search_content]" id="senryu_search_content">
  <% end %>
</div>  
<%= render 'headers_footers/nav_bar' %>

app/views/headers_footers/_user_header.html.erb
<div class="user-header">
  <%= link_to home_senryus_path do %>
    <i class="fas fa-long-arrow-alt-left">&nbsp;&nbsp;</i>
  <% end %>
  <p><%= @user.name %></p>  
</div>
<% unless current_page?(controller: 'users', action: 'show') %>
  <%= render 'headers_footers/relationship_header' %>
<% end %>