config/routes.rb
Rails.application.routes.draw do
  root 'yoin#top'
  resources :users, only: %w(new create edit update show destroy) do
    member do
      get :following, :followers, :collection
    end
  end
  resources :sessions, only: %w(new create destroy)
  resources :senryus, only: %w(new create destroy) do
    collection do
      get :discover, :home
    end
    resources :favorites, only: %w(create destroy)
  end
  resources :relationships, only: %w(create destroy)
end

app/models/user.rb
class User < ApplicationRecord
  has_many :senryus, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_senryus, through: :favorites, source: :senryu
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  mount_uploader :icon, IconUploader

  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password, presence: true, length: { minimum: 6 }, on: :update, unless: Proc.new { |user| user.password.blank? }
  validates :bio, length: { maximum: 150 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  before_action :set_user, only: %i[edit update destroy following followers collection]
  
  def new
    if logged_in?
      redirect_to user_url(current_user.id)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to home_senryus_url, notice: I18n.t('controllers.notices.logged_in')
    else
      render 'new'
    end
  end

  def edit
    not_allow
  end

  def update
    if @user.update(user_params)
      redirect_to user_url(current_user.id), notice: I18n.t('controllers.notices.editted_profile')
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @senryus = @user.senryus.timeline
  end

  def destroy
    @user.destroy
    redirect_to new_user_url, notice: I18n.t('controllers.notices.chao')
  end

  def following
    @users = @user.following
  end

  def followers
    @users = @user.followers
  end

  def collection
    @senryus = @user.favorite_senryus.timeline
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon, :icon_cache, :bio)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def not_allow
    redirect_to user_url(current_user.id) unless @user == current_user
  end
end

app/views/users/_follow.html.erb
<% if current_page?(controller: 'users', action: 'show') %>
  <div id="follow_form_<%= user.id %>">
    <% unless current_user.following?(user) %>
      <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
        <%= f.hidden_field :followed_id %>
        <%= f.submit I18n.t('views.to_follow'), id: "button-in-profile" %>
      <% end %>
    <% else %>
      <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete) do |f| %>
        <%= f.submit I18n.t('views.quit_following'), id: "button-in-profile" %>
      <% end %>
    <% end %>
  </div>
<% else %>
  <div id="follow_form_<%= user.id %>">
    <% unless current_user.following?(user) %>
      <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
        <%= f.hidden_field :followed_id %>
        <%= f.submit I18n.t('views.to_follow'), id: "button-in-relationship" %>
      <% end %>
    <% else %>
      <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete) do |f| %>
        <%= f.submit I18n.t('views.quit_following'), id: "button-in-relationship" %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/_number_of_followers.html.erb
<div id="user_<%= user.id %>_followers">
  <%= link_to followers_user_path(user.id), class: "number-linked" do %>
    <div><%= number_to_human(user.followers.size, :units => {hundred: "百",thousand: "千", million: "百万"}) %></div>
    <p><%= I18n.t('views.followers') %></p>
  <% end %>
</div>

app/views/users/collection.html.erb
<%= render 'headers_footers/collection_header' %>
<%= render 'senryus/index' %>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |f| %>

  <div class="decide-to-update-or-no">
    <%= link_to user_path(@user.id) do %>
      <i class="fas fa-long-arrow-alt-left">
        &nbsp;&nbsp;<%= I18n.t('views.editting_profile') %>
      </i>
    <% end %>
    <%= f.submit I18n.t('views.done')%>
  </div>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h5><%= @user.errors.count %><%= I18n.t('views.errors_count') %></h5>
      <ul id="error_explanation_in_edit_profile">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="edit-icon-field">
    <%= image_tag(@user.icon.url, class: "profile-icon") %>

    <div class="icon-preview"></div>

    <label for="select_icon">
      <%= I18n.t('views.change_profile_icon')%>
      <%= f.file_field :icon, id: "select_icon" %>
    </label>
    
    <%= f.hidden_field :icon_cache %>
  </div>

  <div class="edit-profile-field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: I18n.t('views.user_name_char_limit') %>
  </div>

  <div class="edit-profile-field">
    <%= f.label :bio %>
    <%= f.text_area :bio, placeholder: I18n.t('views.user_bio_char_limit') %>
  </div>

  <div class="edit-details">
    <a href="#" class="open-edit-details">
      <%= I18n.t('views.edit_details')%>
    </a>
  </div>

  <div class="edit-details-content">
    <div class="edit-profile-field">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
  
    <div class="edit-profile-field">
      <%= f.label I18n.t('views.new_password') %>
      <%= f.password_field :password, placeholder: I18n.t('views.minimum_password_length') %>
    </div>
  
    <div class="edit-profile-field">
      <%= f.label I18n.t('views.new_password_confirmation') %>
      <%= f.password_field :password_confirmation %>
    </div>

    <%= link_to I18n.t('views.withdraw'), user_path(current_user.id), method: :delete, data: { confirm: '本当に退会されますか？' } %>
  </div>
<% end %>

<script>
  $(function() {
    //画像ファイルプレビュー表示のイベント追加 fileを選択時に発火するイベントを登録
    $("form").on("change", 'input[type="file"]', function(e) {
      var file = e.target.files[0],
        reader = new FileReader(),
        $preview = $(".icon-preview");
        $original = $(".profile-icon");
      t = this; 

      // 画像ファイル以外の場合は何もしない
      if (file.type.indexOf("image") < 0) {
        return false;
      } 

      // ファイル読み込みが完了した際のイベント登録
      reader.onload = (function(file) {
        return function(e) {
          //既存のプレビューを削除
          $preview.empty();
          $original.remove();
          // .prevewの領域の中にロードした画像を表示するimageタグを追加
          $preview.append(
            $("<img>").attr({
              src: e.target.result,
              class: "icon-preview-img",
              title: file.name
            })
          );
        };
      })(file); 

      reader.readAsDataURL(file);
    });
  });
</script>

app/views/users/followers.html.erb
<%= render 'headers_footers/user_header' %>
<% @users.each do |user| %>
  <div class="relationship-list-outer">
    <div class="user-info">
    <%= link_to user_path(user.id), class: "profile-icon-link" do %>
      <%= image_tag(user.icon.url, class: "relationship-profile-icon") %>
    <% end %>
    <%= link_to "#{user.name}", user_path(user.id), class: "user-name-in-relationship" %>
    </div>
    <%= render partial: 'users/follow', locals: { user: user } unless current_user == user %>
  </div>
<% end %>

app/views/users/following.html.erb
<%= render 'headers_footers/user_header' %>
<% @users.each do |user| %>
  <div class="relationship-list-outer">
    <div class="user-info">
    <%= link_to user_path(user.id), class: "profile-icon-link" do %>
      <%= image_tag(user.icon.url, class: "relationship-profile-icon") %>
    <% end %>
    <%= link_to "#{user.name}", user_path(user.id), class: "user-name-in-relationship" %>
    </div>
    <%= render partial: 'users/follow', locals: { user: user } unless current_user == user %>
  </div>
<% end %>

app/views/users/new.html.erb
<%= link_to root_path, class: "back-arrow" do %>
  <i class="fas fa-chevron-left"></i>
<% end %>

<div class="sign-up-title">
  <h1>Create</h1>
  <h1>Account</h1>
</div>

<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h5><%= @user.errors.count %><%= I18n.t('views.errors_count') %></h5>
    <div id="error_explanation_in_sign_up">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
  <% end %>
  
  <div class="sign-up-field">
    <%= f.label :name %>
    <%= f.text_field :name ,class: "sign-up-input", placeholder: I18n.t('views.user_name_char_limit')%>
    <div class="underline"></div>
  </div>

  <div class="sign-up-field">
    <%= f.label :email %>
    <%= f.email_field :email ,class: "sign-up-input" %>
    <div class="underline"></div>
  </div>

  <div class="sign-up-field">
    <%= f.label :password %>
    <%= f.password_field :password ,class: "sign-up-input", placeholder: I18n.t('views.minimum_password_length') %>
    <div class="underline"></div>
  </div>

  <div class="sign-up-field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation ,class: "sign-up-input" %>
    <div class="underline"></div>
  </div>

  <div class="sign-up-action">
    <h2>Sign up</h2>
    <button type="submit" class="round-shaped-submit" id="sign-up">
      <i class="fas fa-arrow-right"></i>
    </button>
  </div>

<% end %>

app/views/users/show.html.erb
<%= render 'headers_footers/user_header' %>

<div class="profile-container">
  <div class="profile-icon-wrapper">
    <%= image_tag(@user.icon.url, class: "profile-icon") %>
  </div>
  <div class="profile-content">
    <h6><%= @user.name %></h6>
    <p><%= @user.bio %></p>
  </div>
</div>

<div class="numbers-related-to-user">
    <div class="number-linked-outer">
      <%= link_to following_user_path(@user.id), class: "number-linked" do %>
        <div><%= number_to_human(@user.following.size, :units => {hundred: "百",thousand: "千", million: "百万"}) %></div>
        <p><%= I18n.t('views.following') %></p>
      <% end %>
    </div>
    <div class="number-linked-outer">
      <%= render partial: 'users/number_of_followers', locals: { user: @user } %>
    </div>
    <div class="number-linked-outer">
      <%= link_to collection_user_path(@user.id), class: "number-linked" do %>
        <div><%= number_to_human(@user.favorite_senryus.size, :units => {hundred: "百",thousand: "千", million: "百万"}) %></div>
        <p><%= I18n.t('views.my_collection') %></p>
      <% end %>
    </div>
</div>

<div class="button-in-profile-container">
  <% if current_user == @user %>
    <%= form_with(model: @user, local: true, url: edit_user_path(@user.id), method: :get) do |f| %>
      <%= f.submit I18n.t('views.editting_profile'), id: "button-in-profile", class: "edit-profile-button" %>
    <% end %>
  <% else %>
    <%= render partial: 'users/follow', locals: { user: @user } %>
  <% end %>
</div>

<%= render 'senryus/index' %>