config/routes.rb
Rails.application.routes.draw do
  root 'yoin#top'
  resources :users, only: %w(new create edit update show destroy) do
    member do
      get :following, :followers, :collection
    end
  end
  resources :sessions, only: %w(new create destroy)
  resources :senryus, only: %w(new create destroy) do
    collection do
      get :discover, :home
    end
    resources :favorites, only: %w(create destroy)
  end
  resources :relationships, only: %w(create destroy)
end

app/models/senryu.rb
class Senryu < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  include SearchCop
  search_scope :search do
    attributes :first_line, :second_line, :third_line
  end

  scope :subscribed_and_mine, -> (following, me) { where(user_id: following).or(Senryu.where(user_id: me)) }
  scope :discover_senryus, -> (params) { search(params.dig(:senryu, :search_content)) if params.dig(:senryu, :search_content)}
  scope :timeline, -> { order(created_at: :desc) }
  
  def favorited(user_id)
    favorites.find_by(user_id: user_id)
  end

  [:first_line, :second_line, :third_line].each do |attribute|
    if attribute == :second_line
      validates attribute, seven_char_length: true
      validates attribute, ng_word: true
      validates attribute, hiragana_only: true
    else
      validates attribute, five_char_length: true
      validates attribute, ng_word: true
      validates attribute, hiragana_only: true
    end
  end
end

app/controllers/senryus_controller.rb
class SenryusController < ApplicationController
  def discover
    @senryus = Senryu.all.includes(:user, :favorites).discover_senryus(params).timeline
  end

  def home
    @senryus = Senryu.all.includes(:user, :favorites).subscribed_and_mine(current_user.following, current_user).timeline
  end

  def new
    if params[:senryu].present?
      @senryu_with_errors = current_user.senryus.build(senryu_content)
      @senryu_with_errors.save
      @senryu = current_user.senryus.build(senryu_content_without_initial)
      
      @first_initial = params.dig(:senryu, :first_initial)
      @second_initial = params.dig(:senryu, :second_initial)
      @third_initial = params.dig(:senryu, :third_initial)
    else
      @senryu = Senryu.new
    end
  end

  def create
    @senryu = current_user.senryus.build(senryu_content)
    if @senryu.save
      redirect_to home_senryus_url, notice: I18n.t('controllers.notices.posted_senryu')
    else
      redirect_to new_senryu_url(senryu: senryu_params)
    end
  end

  def destroy
    set_senryu
    @senryu.destroy
    redirect_to home_senryus_url, notice: I18n.t('controllers.notices.deleted_senryu')
  end

  private

  def senryu_params
    params.fetch(:senryu, {}).permit %i[first_initial first_line second_initial second_line third_initial third_line]
  end

  def senryu_content
    {
      "first_line": senryu_params[:first_initial] + senryu_params[:first_line], 
      "second_line": senryu_params[:second_initial] + senryu_params[:second_line], 
      "third_line": senryu_params[:third_initial] + senryu_params[:third_line]
    }
  end

  def senryu_content_without_initial
    {
      "first_line": senryu_params[:first_line], 
      "second_line": senryu_params[:second_line], 
      "third_line": senryu_params[:third_line]
    }
  end

  def set_senryu
    @senryu = Senryu.find(params[:id])
  end
end

app/helpers/senryus_helper.rb
module SenryusHelper
  def three_random_initials
    hiragana = ("あ".."ん").to_a
    not_want = ["ぁ", "ぃ", "ぅ", "ぇ", "ぉ", "っ", "ゃ", "ゅ", "ょ", "ゎ", "ゐ", "ゑ", "を", "ん", "づ", "ぢ"]
    initial_array = hiragana - not_want
    initial_array.sample(3)
  end

  def first_initial
    three_random_initials[0]
  end

  def second_initial
    three_random_initials[1]
  end

  def third_initial
    three_random_initials[2]
  end
end

app/views/senryus/_error_messages.html.erb
<div id="error_explanation">
  <h5><%= @senryu_with_errors.errors.count %><%= I18n.t('views.errors_count') %></h5>
  <ul id="error_explanation_in_create_new">
    <% @senryu_with_errors.errors.full_messages.each do |message| %>
      <% if message.include?("捨て仮名") %>
        <li><%= message[/.{3}: /] %><a class="sutegana-rule"></a></li>
      <% else %>
        <li><%= message %></li>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="sutegana-rule-explanation">
  <h6><%= I18n.t('views.sutegana_rule') %></h6>
  <p><%= I18n.t('views.sutegana_rule_explanation_1') %></p>
  <p><%= I18n.t('views.sutegana_rule_explanation_2') %></p>
  <a href="#" class="close-sutegana-rule-explanation">
    <%= I18n.t('views.close_sutegana_rule_explanation') %>
  </a>
</div>

<script>
  $('.sutegana-rule').html('<a href="#" class="sutegana-rule">捨て仮名ルール</a>')
</script>

app/views/senryus/_index.html.erb
<div class="timeline-container">
  <ul class="timeline">
    <% if current_page?(controller: 'senryus', action: 'home') && @senryus.blank?%>
      <%= render 'senryus/suggestion' %>
    <% end %>

    <% @senryus.each do |senryu| %>
      <% if senryu.user == current_user %>
        <li class="timeline-content right">

          <%= link_to "#{senryu.user.name}", user_path(senryu.user.id), class: "author-name" %>

          <%= image_tag(senryu.user.icon.url, class: "timeline-profile-icon") %>

          <span id="favorites_buttons_<%= senryu.id %>", class="favorite-button">
            <%= render partial: 'favorites/favorite', locals: { senryu: senryu } %>
          </span>
          <span>&nbsp;|&nbsp;</span>
          <%= link_to senryu_path(senryu.id), 
          id: "delete_senryu_#{senryu.id}", method: :delete, data: { confirm: I18n.t('views.deleting_post_confirmation') } do %>
            <i class="far fa-trash-alt"></i>
          <% end %>

          <div class="posted-senryu">
            <p class="posted-senryu-line">
              <% 4.times do %>&nbsp;<% end %><%= senryu.first_line %>
            </p>
            <p class="posted-senryu-line">
              <% 12.times do %>&nbsp;<% end %><%= senryu.second_line %>
            </p>
            <p class="posted-senryu-line">
              <% 25.times do %>&nbsp;<% end %><%= senryu.third_line %>
            </p>
          </div>

        </li>
      <% else %>
        <li class="timeline-content left">
          
          <%= link_to "#{senryu.user.name}", user_path(senryu.user.id), class: "author-name" %>

          <%= image_tag(senryu.user.icon.url, class: "timeline-profile-icon") %>
          
          <span id="favorites_buttons_<%= senryu.id %>", class="favorite-button">
            <%= render partial: 'favorites/favorite', locals: { senryu: senryu } %>
          </span>
          
          <div class="posted-senryu-others">
            <p class="posted-senryu-line">
              <% 4.times do %>&nbsp;<% end %><%= senryu.first_line %>
            </p>
            <p class="posted-senryu-line">
              <% 12.times do %>&nbsp;<% end %><%= senryu.second_line %>
            </p>
            <p class="posted-senryu-line">
              <% 25.times do %>&nbsp;<% end %><%= senryu.third_line %>
            </p>
          
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/senryus/_search.html.erb
<div class="search-form">
  <%= form_with(model: @senryus, local: true, method: :get, url: discover_senryus_path) do |f| %>
    <input class="useFontAwesomeFamily" type="text" placeholder="けんさくする" name="senryu[search_content]" id="senryu_search_content">
  <% end %>
</div>  

app/views/senryus/_suggestion.html.erb
<li class="timeline-content">
  <a href="#", class="someone-name">Someone</a>
  <img class="timeline-profile-icon" src="https://randomuser.me/api/portraits/women/18.jpg" alt="">
  <div class="posted-senryu">
    <p class="someone-talking"><%= I18n.t('views.greeting') %><%= current_user.name %></p>
    <p class="someone-talking"><%= I18n.t('views.wanna_enjoy?') %></p>
  </div>
</li>
<li class="timeline-content">
  <a href="#", class="someone-name">Someone</a>
  <img class="timeline-profile-icon" src="https://randomuser.me/api/portraits/women/18.jpg" alt="">
  <div class="posted-senryu">
    <p class="someone-talking"><%= I18n.t('views.wanna_discover?') %></p>
    <%= link_to I18n.t('views.discover'), discover_senryus_path, class: "someone-talking"%>
  </div>
</li>
<li class="timeline-content">
  <a href="#", class="someone-name">Someone</a>
  <img class="timeline-profile-icon" src="https://randomuser.me/api/portraits/women/18.jpg" alt="">
  <div class="posted-senryu">
    <p class="someone-talking"><%= I18n.t('views.wanna_compose?') %></p>
    <%= link_to I18n.t('views.compose'), new_senryu_path, class: "someone-talking"%>
  </div>
</li>

app/views/senryus/discover.html.erb
<%= render 'headers_footers/search_header' %>
<%= render 'senryus/index' %>

app/views/senryus/home.html.erb
<%= render 'headers_footers/home_header' %>
<%= render 'senryus/index' %>

app/views/senryus/index.html.erb
<h1>Senryu#index</h1>


<ul>
  <% @senryus.each do |senryu| %>
    <li>
      <%= senryu.first_line %>・<%= senryu.second_line %>・<%= senryu.third_line %> by <%= senryu.user.name %>
      <%= link_to '<delete>', senryu_path(senryu.id), method: :delete %>
      <div id="favorites_buttons_<%= senryu.id %>">
        <%= render partial: 'favorites/favorite', locals: { senryu: senryu, favorites: @favorites } %>
      </div>
    </li>
  <% end %>
</ul>

app/views/senryus/new.html.erb
<%= link_to home_senryus_path, class: "back-arrow" do %>
  <i class="fas fa-chevron-left"></i>
<% end %>

<% if @senryu_with_errors.nil? %>
  <%
    @first_initial = first_initial
    @second_initial = second_initial
    @third_initial = third_initial
  %>
<% end %>

<h6 class="create-new-intro">Each line you start with ...</h6>

<div class="three-random-initials">
  <div class="initial">
    <%= @first_initial %>
  </div>
  <div class="dot">・</div>
  <div class="initial">
    <%= @second_initial %>
  </div>
  <div class="dot">・</div>
  <div class="initial">
    <%= @third_initial %>
  </div>
</div>

<%= link_to new_senryu_path do %>
  <i class="fas fa-sync-alt refresh-initials"></i>
<% end %>

<%= form_with(model: @senryu, local: true) do |f| %>

  <% if @senryu_with_errors.present? %>
    <% if @senryu_with_errors.errors.any? %>
      <%= render 'senryus/error_messages' %>
    <% end %>
  <% end %>

  <div class="create-new-card">
    <div class="create-new-card-space"></div>
    <div class="create-new-line-field">
      <%= f.hidden_field :first_initial, value: "#{@first_initial}" %>
      <div><%= @first_initial %></div><%= f.text_field :first_line, placeholder: I18n.t('views.four_syllable') %>
    </div>
  
    <div class="create-new-line-field">
      <%= f.hidden_field :second_initial, value: "#{@second_initial}" %>
      <div><%= @second_initial %></div><%= f.text_field :second_line, placeholder: I18n.t('views.six_syllable') %>
    </div>
  
    <div class="create-new-line-field">
      <%= f.hidden_field :third_initial, value: "#{@third_initial}" %>
      <div><%= @third_initial %></div><%= f.text_field :third_line, placeholder: I18n.t('views.four_syllable') %>
    </div>
  
    <div class="compose-action">
      <%= f.submit I18n.t('views.compose') %>
    </div>
  </div>
<% end %>